### ISSUE TITLE
Incorrect assignment in case of pointer to alias of slice

### ISSUE THREAD

**Issue by jvergison** [pquerna/ffjson#243]
Consider following declared types, as found in the [github.com/golang/geo/s2](github.com/golang/geo/s2) package:

```
package s2

type CellID uint64
type CellUnion []CellID

```

This package is then used in another file as follows:

```
type Filter struct {
  Cells *s2.CellUnion `json:"cells"`
}
```

Running ffjson for this file produces the following code, and no error messages:
` j.Cells = &[]s2.CellID{}`

However, this produces the following error when building:

> cannot use []s2.CellID literal (type *[]s2.CellID) as type *s2.CellUnion in assignment

The correct code in this case would be

```
cu := s2.CellUnion([]s2.CellID{})
j.Cells = &cu
```

**Comment by erikdubbelboer** [comment]
See https://github.com/pquerna/ffjson/pull/244

**Comment by andersfylling** [comment]
Has anyone verified PR #244 to actually work?
It lacks unit tests, so I'm just curious.

**Comment by erikdubbelboer** [comment]
@andersfylling I have :) but I missed the question for a test case. I'll add this this weekend.

**Comment by erikdubbelboer** [comment]
@andersfylling I have updated the pull request with a test case.

**Comment by jflipts** [comment]
This issue is still present in the current master branch, when will the fix be merged?
